[package]
name = "deploy-smart-contract-example"
version = "0.1.0"
edition = "2021"


[dependencies]
ethers = "2.0.9"
hex = "0.4.3"
ethers-providers = "2.0.9"
tokio = {version = "1.32.0", features = [ "macros"]}
anyhow = "1.0.75"
